// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using V3RII.Infrastructure.Persistence;

#nullable disable

namespace V3RII.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(V3RiiDbContext))]
    [Migration("20260706113633_AddSupportOperationsAndRag")]
    partial class AddSupportOperationsAndRag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("V3RII.Domain.Entities.ChatAnalyticsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Intent")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("Product")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "CreatedAt");

                    b.HasIndex("Product", "CreatedAt");

                    b.ToTable("ChatAnalyticsEvents");
                });

            modelBuilder.Entity("V3RII.Domain.Entities.KnowledgeArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("Product")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Product", "IsPublished");

                    b.ToTable("KnowledgeArticles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContentMarkdown = "Müşteri kartları, mükerrer kayıt kontrolü, teklif-sipariş dönüşümü, PDF rapor tasarımı, Power BI, Outlook, WhatsApp ve Netsis/ERP entegrasyonları desteklenir.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsPublished = true,
                            Product = 1,
                            Summary = "Satış, teklif, müşteri 360, onay akışları, mail/WhatsApp ve ERP entegrasyonları için kurumsal CRM.",
                            Tags = "crm,satis,teklif,netsis,erp,whatsapp",
                            Title = "V3RII CRM"
                        },
                        new
                        {
                            Id = 2L,
                            ContentMarkdown = "Mal kabul, depo giriş/çıkış, transfer, karantina, kalite kontrol, paketleme, yükleme, barkod, e-belge ve ERP entegrasyon süreçleri parametrik olarak yönetilebilir.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsPublished = true,
                            Product = 3,
                            Summary = "Depo kabul, lokasyon, barkod, sevkiyat, kalite kontrol, paketleme ve ERP servis operasyonlarını yönetir.",
                            Tags = "wms,depo,barkod,sevkiyat,netsis,erp",
                            Title = "V3RII WMS"
                        });
                });

            modelBuilder.Entity("V3RII.Domain.Entities.MailOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SentAt", "NextAttemptAt");

                    b.ToTable("MailOutboxItems");
                });

            modelBuilder.Entity("V3RII.Domain.Entities.PermissionDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PermissionDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "support.tickets.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "support.tickets.read"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "support.tickets.manage",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "support.tickets.manage"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "support.knowledge.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "support.knowledge.read"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "support.knowledge.manage",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "support.knowledge.manage"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "support.analytics.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "support.analytics.read"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "admin.users.manage",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "admin.users.manage"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "system.hangfire.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seeded system permission",
                            IsDeleted = false,
                            Name = "system.hangfire.read"
                        });
                });

            modelBuilder.Entity("V3RII.Domain.Entities.PermissionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("PermissionGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "System Admin",
                            NormalizedName = "SYSTEM ADMIN"
                        });
                });

            modelBuilder.Entity("V3RII.Domain.Entities.PermissionGroupPermissionDefinition", b =>
                {
                    b.Property<long>("PermissionGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionDefinitionId")
                        .HasColumnType("bigint");

                    b.HasKey("PermissionGroupId", "PermissionDefinitionId");

                    b.HasIndex("PermissionDefinitionId");

                    b.ToTable("PermissionGroupPermissionDefinitions");

                    b.HasData(
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 1L
                        },
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 2L
                        },
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 3L
                        },
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 4L
                        },
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 5L
                        },
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 6L
                        },
                        new
                        {
                            PermissionGroupId = 1L,
                            PermissionDefinitionId = 7L
                        });
                });

            modelBuilder.Entity("V3RII.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandoffReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Product")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresHandoff")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TranscriptJson")
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TicketNo")
                        .IsUnique();

                    b.HasIndex("Status", "Product", "CreatedAt");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("V3RII.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@v3rii.com",
                            FullName = "V3RII Admin",
                            IsActive = true,
                            IsDeleted = false,
                            NormalizedEmail = "ADMIN@V3RII.COM",
                            PasswordHash = "$2a$11$5SVbkfIquQrVSkCTMo9iq.wbO.O2MejZMlChqiuxWwoLFC.rjPEeq"
                        });
                });

            modelBuilder.Entity("V3RII.Domain.Entities.UserPermissionGroup", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "PermissionGroupId");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("UserPermissionGroups");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            PermissionGroupId = 1L
                        });
                });

            modelBuilder.Entity("V3RII.Domain.Entities.PermissionGroupPermissionDefinition", b =>
                {
                    b.HasOne("V3RII.Domain.Entities.PermissionDefinition", "PermissionDefinition")
                        .WithMany()
                        .HasForeignKey("PermissionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("V3RII.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionDefinition");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("V3RII.Domain.Entities.UserPermissionGroup", b =>
                {
                    b.HasOne("V3RII.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("Users")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("V3RII.Domain.Entities.User", "User")
                        .WithMany("PermissionGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("V3RII.Domain.Entities.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("V3RII.Domain.Entities.User", b =>
                {
                    b.Navigation("PermissionGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
